stages:
  - lint
  - check

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

lint-job:
  stage: lint
  image: python:3.10-slim
  before_script:
    - pip install flake8 black
  script:
    - echo "Executando verificação de formatação e lint..."
    - black --check core/ cli/ || echo "Black encontrou problemas de formatação, mas continuaremos a execução."
    - flake8 core/ cli/ --max-line-length=120 --extend-ignore=E203,W503,E501,E402

check-job:
  stage: check
  image: python:3.10-slim
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends gcc libsqlite3-dev
    - pip install -r requirements.txt
  script:
    - echo "Verificando compilação e dependências..."
    - python -m compileall core/ cli/