import urllib3
import time

from core.models.lara import Lara
from core.services.document_service import DocumentService

# urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

lara = Lara()
# # print(lara.filter_cig_minutes_webpage('https://www.jardimbotanico.df.gov.br/conheca-a-lei-de-acesso-a-informacao/'))
# # print(lara.filter_portal_webpage('https://www.jardimbotanico.df.gov.br/conheca-a-lei-de-acesso-a-informacao/'))
lara.generate_report()

# generator = DocumentService()

# # Dados para a tabela
# data = [
#     ["Name", "Age", "Occupation"],
#     ["Alice", "30", "Engineer"],
#     ["Bob", "25", "Designer"],
#     ["Charlie", "35", "Manager"]
# ]

# # Gerar o documento com título e tabela
# title = "Employee Information"
# filename = "employee_table"
# generator.create_document_with_table(title=title, data=data, filename=filename)

# if __name__ == "__main__":
#     service = DocumentService()

    # # Exemplo de documento básico
    # path = service.create_document(
    #     title="Meeting Summary",
    #     content=[
    #         "This document contains the minutes of the last meeting.",
    #         "Main points discussed were: project deadlines, team performance, and resource allocation."
    #     ],
    #     footer="Generated by DocumentService",
    #     file_name="meeting_summary.docx"
    # )
    # print(f"Document created at: {path}")

    # # Exemplo de relatório detalhado
    # report_data = {
    #     "Introduction": ["This report provides an overview of recent developments."],
    #     "Financial Performance": [
    #         "Revenue increased by 15% this quarter.",
    #         "Expenses remained stable compared to last quarter."
    #     ],
    #     "Future Outlook": [
    #         "Expecting a 10% growth in revenue for the next quarter.",
    #         "Key focus areas will include marketing and product development."
    #     ],
    # }

    # report_path = service.generate_report(report_data, file_name="quarterly_report.docx")
    # print(f"Report created at: {report_path}")

# lara.get_pdf_links('https://www.sedes.df.gov.br/comite-interno-de-governanca-publica-cigp/')

# excel = "FAPDF-Segmentoseitensintegridade(versão20.04.Completo)_corrigido(1).xlsx"
# dados = lara.read_excel_data(excel)
# if dados == None:
#     print(f"Erro ao ler o arquivo: {excel}")
    
# url_google = "https://google.com/search?q="
# header = {
#     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'}

# param = " atas comitê interno de governança"

# adm_direta = []
# mista_publica = []

# if lara.load_orgaos_name(adm_direta, mista_publica) == 1:
#     print("Erro ao carregar os nomes dos órgões")    
#     # orgao = nome

# dict_general : dict[str, list[str]]
# for orgao in adm_direta:
#     dict_general.update(lara.search_link_cig(lara.company_acronym(orgao), orgao,
#                      param, url_google, header, 6))
#     time.sleep(7)

# # print(f"Dicionario geral {dict_general}")
# resul, acertos, total_com_ata, total_sem_ata = lara.compare_maps(dados, dict_general)
# list_orgaos = lara.filter_dict_orgaos(dict_general)

# print("Total com ata: " + str(total_com_ata))
# print("Total sem ata: " + str(total_sem_ata))
# print("Quantidade de Acertos: " + str(acertos))
# print("Porcentagem de Acertos: " + str((acertos/total_com_ata)*100))
# for orgoao, tem_atas in resul.items():
#     print(f"{orgoao}: {tem_atas}")

exit(0)

for orgao in adm_direta:
    dict_lol = search_link_cig2(company_acronym(orgao), orgao,
                                param, url_google, header, 6)
    time.sleep(7)
    for key, value in dict_lol.items():
        for link in value:
            link = link.split("=", 1)[1]

            link = "https://fap.df.gov.br/atas-cig-2022/"
            # ft1, _ = filter_webpage_type1(link, key)        
            ft2, tem_ata, data = filter_webpage_type2(link, key)
    
            # if (ft1):
            #     print(f"Página das atas: {link}")
            if (ft2):
                print(f"Portal CIG: {link}")
                if (tem_ata):
                    print("Portal CIG com atas acessíveis")
            else:
                print(f"Não é portal CIG: {link}")
            exit(0)
            # if (not ft1 and not ft2):
            #     print(f"Não é nenhum dos dois: {link}")

# for orgao in adm_direta:
#     dict_lol = search_link_cig2(company_acronym(orgao), orgao,
#                      param, url_google, header, 6)
#     time.sleep(7)

# print(dict_lol)
# resul, acertos, total = comparar_mapas(dados, dict_lol)

# print("Total: " + str(total))
# print("Quantidade de Acertos: " + str(acertos))
# print("Porcentagem de Acertos: " + str((acertos/total)*100))
# for orgoao, tem_atas in resul.items():
#     print(f"{orgoao}: {tem_atas}")

exit(0)
dict_1 = {}
dict_2 = {}
dict_excluidos = {}

for key, value in dict_lol.items():
    for link in value:
        if (filter_webpage_type1(link, key)):
            dict_1.setdefault(key, []).append(link)
        elif (filter_webpage_type2(link, key)):
            dict_2.setdefault(key, []).append(link)
        else:
            dict_excluidos.setdefault(key, []).append(link)

print("\n\n\n\n\n")
print(dict_lol)


# Usar esse código depois
# source = requests.get(url)

# soup = BeautifulSoup(source.text, 'html.parser')

# links_ata_por_ano = []
#
# for link in soup.find_all('a'):
#     if ("atas" in str(link.get('href')) and "reunioes" in str(link.get('href'))):
#         links_ata_por_ano.append(link.get('href'))

# for links in links_ata_por_ano:
#     source = requests.get(links)
#     soup = BeautifulSoup(source.text, 'html.parser')

#     for link in soup.find_all('a'):
#         if ("facebook" in str(link.get('href')).lower() or "twitter" in str(link.get('href')).lower()):
#             continue

#         if ("ata" in str(link.get('href')).lower() or (".pdf" in str(link.get('href')).lower()) or "reuniao" in str(link.get('href')).lower()):
#             print(link.get('href'))


# class Ementa:
#     def __init__(self, orgao_name: str, ementa_titulo: str, data: str, link_arquivo: str):
#         self.__orgao_name__ = orgao_name
#         self.__ementa_titulo__ = ementa_titulo
#         self.__data__ = data
#         self.__link_arquivo__ = link_arquivo

#     def set_ementa_titulo(self, ementa_titulo: str):
#         self.__ementa_titulo__ = ementa_titulo

#     def set_data(self, data: str):
#         self.__data__ = data

#     def set_link_arquito(self, link_arquivo: str):
#         self.__link_arquivo__ = link_arquivo

#     def set_orgao_name(self, orgao_name: str):
#         self.__orgao_name__ = orgao_name

#     def __repr__(self) -> str:
#         return f"Orgão: {self.__orgao_name__}\nTítulo: {self.__ementa_titulo__}\nData: {self.__data__}\nLinks: {self.__link_arquivo__}\n"

# # Função para encontrar a sigla do orgão do distrito federal


# # Função para raspar as informações das ementas: título, data e link da ementa
# def search_companay_by_acronym(acronym: str, orgao_list: list) -> list:
#     options = webdriver.FirefoxOptions()
#     options.add_argument("-headless")
#     driver = webdriver.Firefox(options=options)
#     print(acronym)
#     driver.get(f"https://www.sinj.df.gov.br/sinj/ResultadoDePesquisa?tipo_pesquisa=geral&all=Pol%C3%ADtica+de+Integridade+P%C3%BAblica+{acronym}")

#     quadros = driver.find_elements(By.CSS_SELECTOR, 'div.column.w-90-pc.text-justify.ds_ementa')
#     quadros = [quadro.text for quadro in quadros]
#     orgao_list.append(quadros)

#     datas = driver.find_elements(By.CSS_SELECTOR, 'span.dt_assinatura.dt_assinatura_text')
#     datas = [str(data.text).split()[0] for data in datas]
#     orgao_list.append(datas)

#     links_arquivos = driver.find_elements(By.CLASS_NAME, 'baixarArquivo')
#     links_arquivos = [link.get_attribute("href") for link in links_arquivos]
#     orgao_list.append(links_arquivos)


#     driver.implicitly_wait(100)
#     driver.quit()
#     return orgao_list

# def filtrar_ementas(ementas: list) -> list:
#     ementas_filtradas = []
#     print(ementas)
#     for ementa in ementas:
#         if ("Política de Integridade Pública" not in ementa.__ementa_titulo__ and "Política de Gestão de Riscos" not in ementa.__ementa_titulo__):
#             continue
#         ano = int(ementa.__data__.split('/')[2])
#         if not ano >= 2022:
#             continue
#         ementas_filtradas.append(ementa)

#     return ementas_filtradas

# # Criando um exemplo de lista de orgãos
# orgaos = [ ["Secretaria De Estado De Educação Do Distrito Federal"], ["Secretaria De Estado De Planejamento, Orçamento E Administração Do Distrito Federal"], ["Instituto De Assistência À Saúde Dos Servidores Do Distrito Federal"] ]
# # Lista que vai conter todos os objetos Ementa
# ementa_objs = []

# # Raspa as informações da web e vai criar uma lista encadeada das informações das ementas de cada orgão
# for orgao_list in orgaos:
#     acronym = company_acronym(orgao_list[0])
#     search_companay_by_acronym(acronym=acronym, orgao_list=orgao_list)
#     # driver.get("https://www.sinj.df.gov.br/sinj/ResultadoDePesquisa?tipo_pesquisa=geral&all=Pol%C3%ADtica+de+Integridade+P%C3%BAblica+{acronym}")

#     # quadros = driver.find_elements(By.CSS_SELECTOR, 'div.column.w-90-pc.text-justify.ds_ementa')
#     # orgao_list.append(quadros
#     #                   )
#     # datas = driver.find_elements(By.CSS_SELECTOR, 'span.dt_assinatura.dt_assinatura_text')
#     # orgao_list.append(datas)

#     # links_arquivos = driver.find_elements(By.CLASS_NAME, 'baixarArquivo')
#     # orgao_list.append(links_arquivos)

# print("---------------------\n\n")

# # Instâncianeo os objetos com as informações coletadas e armazenadas na orgao
# for orgao_list in orgaos:
#     for i in range(len(orgao_list)):
#         for j in range(len(orgao_list[1])):
#             ementa_objs.append(Ementa( orgao_list[0], orgao_list[1][j], orgao_list[2][j], orgao_list[3][j] ))

# ementas = filtrar_ementas(ementa_objs)
# company_dict = {}
# for ementa in ementas:
#     company_dict.setdefault(ementa.__orgao_name__, []).append(ementa.__link_arquivo__)


# link = company_dict['Secretaria De Estado De Educação Do Distrito Federal'][0]
# source = requests.get(link, stream=True)
# soup = BeautifulSoup(source.text, 'html.parser')

# with open("ementa_teste.txt", 'wb') as file:
#     file.write(soup.get_text('\n', '\n').encode())

# print(company_dict)
